channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - dask=2024.4.1
  - distributed=2024.4.1
  - dask-image=2023.08.1
  - flatten_json
  - numpy>=1.26.0
  - pyyaml
  - scikit-image>=0.21.0
  - tqdm=4.66.1
  - zarr=2.16.1
  - pip:
    - ome-types
